# Generated by Django 3.0.2 on 2020-04-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
